version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: userscrud-mysql
    restart: unless-stopped
    command: 
      - --innodb_force_recovery=0
      - --default_time_zone=America/Sao_Paulo
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userscrud
      - MYSQL_TCP_PORT=3306
    volumes:
      - C:\Users\Rafael\Documents\Projects\car-api\sql-server\db:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
